"""
Regras alinhadas ao propósito do Anexo IV da Resolução nº 1.137/2023 (CONFEA) —
informações usualmente exigidas para registro de CAT em consonância com ART.

Referências são didáticas para apoio ao analista; interpretação final é humana/CREA.
"""

from app.core.constants import (
    CRITICALITY_BAIXA,
    CRITICALITY_CRITICA,
    CRITICALITY_MEDIA,
    NORMATIVE_INFORMATIVO,
    NORMATIVE_OBRIGATORIO,
    NORMATIVE_RECOMENDADO,
)
from app.rules.schemas.rule_definition import NormativeRuleDefinition

RESOLUCAO = "Resolução nº 1.137"
VERSAO = "2023"

RULES_RESOLUCAO_1137: tuple[NormativeRuleDefinition, ...] = (
    NormativeRuleDefinition(
        id="R1137_ANEX4_PROFISSIONAL",
        nome="Identificação do profissional responsável",
        descricao="O documento deve permitir identificar o profissional técnico responsável.",
        resolucao=RESOLUCAO,
        resolucao_versao=VERSAO,
        artigo="Anexo IV (conteúdo mínimo da CAT) — identificação profissional",
        obrigatoriedade=NORMATIVE_OBRIGATORIO,
        campo_relacionado="profissional_nome",
        tipo_validacao="PRESENCA",
        severidade=CRITICALITY_CRITICA,
        funcao_validacao="presence_act_field",
        mensagem_erro="Profissional não identificado no texto extraído do atestado.",
        mensagem_sucesso="Profissional identificado no atestado.",
        impacto_regulatorio="Ausência pode impedir a validação da CAT junto ao acervo técnico.",
    ),
    NormativeRuleDefinition(
        id="R1137_ANEX4_ART_NUMERO",
        nome="Número da ART",
        descricao="O atestado deve referir o número da ART de execução.",
        resolucao=RESOLUCAO,
        resolucao_versao=VERSAO,
        artigo="Anexo IV — vínculo com ART",
        obrigatoriedade=NORMATIVE_OBRIGATORIO,
        campo_relacionado="numero_art",
        tipo_validacao="PRESENCA",
        severidade=CRITICALITY_CRITICA,
        funcao_validacao="presence_act_field",
        mensagem_erro="Número da ART não localizado no texto do atestado.",
        mensagem_sucesso="Número da ART presente no atestado.",
        impacto_regulatorio="Sem vínculo explícito com a ART, a CAT pode ser considerada incompleta.",
    ),
    NormativeRuleDefinition(
        id="R1137_ANEX4_CNPJ",
        nome="CNPJ do contratante",
        descricao="Identificação fiscal do contratante no documento.",
        resolucao=RESOLUCAO,
        resolucao_versao=VERSAO,
        artigo="Anexo IV — contratante",
        obrigatoriedade=NORMATIVE_OBRIGATORIO,
        campo_relacionado="cnpj",
        tipo_validacao="PRESENCA",
        severidade=CRITICALITY_CRITICA,
        funcao_validacao="presence_act_field",
        mensagem_erro="CNPJ do contratante não identificado no texto extraído.",
        mensagem_sucesso="CNPJ do contratante identificado no atestado.",
        impacto_regulatorio="Inconsistência ou ausência de CNPJ prejudica conferência contratual e fiscal.",
    ),
    NormativeRuleDefinition(
        id="R1137_ANEX4_OBJETO",
        nome="Objeto técnico / serviços",
        descricao="Descrição do objeto dos serviços ou empreitada.",
        resolucao=RESOLUCAO,
        resolucao_versao=VERSAO,
        artigo="Anexo IV — objeto",
        obrigatoriedade=NORMATIVE_OBRIGATORIO,
        campo_relacionado="objeto",
        tipo_validacao="PRESENCA",
        severidade=CRITICALITY_MEDIA,
        funcao_validacao="presence_act_field",
        mensagem_erro="Objeto do serviço não localizado no texto do atestado.",
        mensagem_sucesso="Objeto do serviço descrito no atestado.",
        impacto_regulatorio="Objeto incompleto dificulta verificar aderência à ART e à contratação.",
    ),
    NormativeRuleDefinition(
        id="R1137_ANEX4_LOCAL",
        nome="Local da obra ou serviço",
        descricao="Identificação de endereço e/ou município da execução.",
        resolucao=RESOLUCAO,
        resolucao_versao=VERSAO,
        artigo="Anexo IV — localização",
        obrigatoriedade=NORMATIVE_OBRIGATORIO,
        campo_relacionado="municipio_uf",
        tipo_validacao="PRESENCA",
        severidade=CRITICALITY_MEDIA,
        funcao_validacao="presence_act_local",
        mensagem_erro="Local (endereço ou município/UF) não identificado com clareza no atestado.",
        mensagem_sucesso="Local da execução indicado (endereço ou município/UF).",
        impacto_regulatorio="Local divergente ou ausente afeta análise de competência territorial e aderência à ART.",
    ),
    NormativeRuleDefinition(
        id="R1137_ANEX4_PERIODO",
        nome="Período de execução",
        descricao="Prazos ou datas de início/fim da execução.",
        resolucao=RESOLUCAO,
        resolucao_versao=VERSAO,
        artigo="Anexo IV — prazo / período",
        obrigatoriedade=NORMATIVE_OBRIGATORIO,
        campo_relacionado="periodo_execucao",
        tipo_validacao="PRESENCA",
        severidade=CRITICALITY_MEDIA,
        funcao_validacao="presence_act_period",
        mensagem_erro="Período de execução (datas) não identificado no atestado.",
        mensagem_sucesso="Período de execução com datas identificáveis no atestado.",
        impacto_regulatorio="Ausência de prazo dificulta confronto com a vigência da ART.",
    ),
    NormativeRuleDefinition(
        id="R1137_ANEX4_ATIVIDADES",
        nome="Atividades técnicas",
        descricao="Descrição das atividades ou serviços técnicos executados.",
        resolucao=RESOLUCAO,
        resolucao_versao=VERSAO,
        artigo="Anexo IV — atividades",
        obrigatoriedade=NORMATIVE_OBRIGATORIO,
        campo_relacionado="atividades_tecnicas",
        tipo_validacao="PRESENCA",
        severidade=CRITICALITY_BAIXA,
        funcao_validacao="presence_act_field",
        mensagem_erro="Atividades técnicas não localizadas no texto extraído.",
        mensagem_sucesso="Atividades técnicas descritas no atestado.",
        impacto_regulatorio="Descrição genérica pode exigir complementação para certificação.",
    ),
    NormativeRuleDefinition(
        id="R1137_ANEX4_QUANTITATIVOS",
        nome="Quantitativos / memorial",
        descricao="Quantidades ou referência a quantitativos da obra/serviço.",
        resolucao=RESOLUCAO,
        resolucao_versao=VERSAO,
        artigo="Anexo IV — quantitativos",
        obrigatoriedade=NORMATIVE_RECOMENDADO,
        campo_relacionado="quantitativos",
        tipo_validacao="PRESENCA",
        severidade=CRITICALITY_BAIXA,
        funcao_validacao="presence_act_field",
        mensagem_erro="Quantitativos não identificados no texto do atestado.",
        mensagem_sucesso="Quantitativos ou referência quantitativa presente.",
        impacto_regulatorio="Ausência pode limitar conferência dimensional com a ART.",
    ),
    NormativeRuleDefinition(
        id="R1137_CONS_NUMERO_ART",
        nome="Consistência do número da ART",
        descricao="O número da ART no atestado deve ser compatível com a ART selecionada.",
        resolucao=RESOLUCAO,
        resolucao_versao=VERSAO,
        artigo="Anexo IV — consistência documental",
        obrigatoriedade=NORMATIVE_OBRIGATORIO,
        campo_relacionado="numero_art",
        tipo_validacao="CONSISTENCIA",
        severidade=CRITICALITY_CRITICA,
        funcao_validacao="consistency_field_compatible",
        mensagem_erro="Número da ART no atestado não compatível com a ART de referência.",
        mensagem_sucesso="Número da ART compatível com o cadastro analisado.",
        impacto_regulatorio="Divergência impedente para vincular a CAT à ART correta.",
    ),
    NormativeRuleDefinition(
        id="R1137_CONS_CNPJ",
        nome="Consistência do CNPJ do contratante",
        descricao="CNPJ extraído confrontado com a ART.",
        resolucao=RESOLUCAO,
        resolucao_versao=VERSAO,
        artigo="Anexo IV — consistência contratual",
        obrigatoriedade=NORMATIVE_OBRIGATORIO,
        campo_relacionado="cnpj",
        tipo_validacao="CONSISTENCIA",
        severidade=CRITICALITY_CRITICA,
        funcao_validacao="consistency_field_compatible",
        mensagem_erro="CNPJ divergente ou não confrontável com a ART.",
        mensagem_sucesso="CNPJ compatível com os dados da ART.",
        impacto_regulatorio="Inconsistência de CNPJ pode impedir validação fiscal/contratual.",
    ),
    NormativeRuleDefinition(
        id="R1137_CONS_MUNICIPIO",
        nome="Consistência de município / UF",
        descricao="Local informado no atestado confrontado com a ART.",
        resolucao=RESOLUCAO,
        resolucao_versao=VERSAO,
        artigo="Anexo IV — localização",
        obrigatoriedade=NORMATIVE_OBRIGATORIO,
        campo_relacionado="municipio_uf",
        tipo_validacao="CONSISTENCIA",
        severidade=CRITICALITY_MEDIA,
        funcao_validacao="consistency_field_compatible",
        mensagem_erro="Município/UF divergente ou não compatível com a ART.",
        mensagem_sucesso="Localização compatível com a ART.",
        impacto_regulatorio="Divergência territorial pode demandar retificação ou nova análise de competência.",
    ),
    NormativeRuleDefinition(
        id="R1137_CONS_OBJETO",
        nome="Compatibilidade do objeto",
        descricao="Objeto do atestado semanticamente alinhado ao da ART.",
        resolucao=RESOLUCAO,
        resolucao_versao=VERSAO,
        artigo="Anexo IV — objeto técnico",
        obrigatoriedade=NORMATIVE_RECOMENDADO,
        campo_relacionado="objeto",
        tipo_validacao="CONSISTENCIA",
        severidade=CRITICALITY_MEDIA,
        funcao_validacao="consistency_objeto_semantic",
        mensagem_erro="Objeto do atestado potencialmente incompatível com a ART.",
        mensagem_sucesso="Objeto compatível ou aceitável frente à ART.",
        impacto_regulatorio="Objeto divergente pode afastar a CAT da realidade contratada.",
    ),
)
