"""Constantes de domínio — comparação e relatórios."""

FIELD_STATUS_COMPATIVEL = "COMPATIVEL"
FIELD_STATUS_AUSENTE = "AUSENTE"
FIELD_STATUS_NAO_IDENTIFICADO = "NAO_IDENTIFICADO"
FIELD_STATUS_DIVERGENTE = "DIVERGENTE"
FIELD_STATUS_NAO_VERIFICADO = "NAO_VERIFICADO"
FIELD_STATUS_NAO_APLICAVEL = "NAO_APLICAVEL"

CRITICALITY_CRITICA = "CRITICA"
CRITICALITY_MEDIA = "MEDIA"
CRITICALITY_BAIXA = "BAIXA"
CRITICALITY_NENHUMA = "NENHUMA"

REVIEW_PENDENTE = "PENDENTE"
REVIEW_REVISADO = "REVISADO"
REVIEW_CORRECAO = "CORRECAO_SOLICITADA"

OVERALL_VERDE = "VERDE"
OVERALL_AMARELO = "AMARELO"
OVERALL_VERMELHO = "VERMELHO"

CNPJ_STATUS_OK = "OK"
CNPJ_STATUS_NAO_VERIFICADO = "NAO_VERIFICADO"
CNPJ_STATUS_DIVERGENTE = "DIVERGENTE"

# Metadados PDF suspeitos (editores gráficos comuns)
# Validação normativa (CONFEA / CREA)
NORMATIVE_STATUS_ATENDIDA = "ATENDIDA"
NORMATIVE_STATUS_NAO_ATENDIDA = "NAO_ATENDIDA"
NORMATIVE_STATUS_ATENCAO = "ATENCAO"

NORMATIVE_GLOBAL_CONFORME = "CONFORME"
NORMATIVE_GLOBAL_PARCIAL = "PARCIAL"
NORMATIVE_GLOBAL_NAO_CONFORME = "NAO_CONFORME"

NORMATIVE_FIELD_SIM = "SIM"
NORMATIVE_FIELD_NAO = "NAO"
NORMATIVE_FIELD_PARCIAL = "PARCIAL"

NORMATIVE_OBRIGATORIO = "OBRIGATORIO"
NORMATIVE_RECOMENDADO = "RECOMENDADO"
NORMATIVE_INFORMATIVO = "INFORMATIVO"

SUSPICIOUS_PDF_CREATORS = (
    "photoshop",
    "gimp",
    "canva",
    "paint",
    "inkscape",
    "figma",
    "coreldraw",
    "microsoft office picture manager",
)
